version: '3'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mongo

  app:
    container_name: combat-connect-api
    image: combat-connect-api
    tty: true
    stdin_open: true
    build:
      context: .
      target: development
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - mongodb

volumes:
  db: